spring:
  application:
    name: hub-service
  profiles:
    active: dev
  config:
    import: 'optional:configserver:'

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost:5435/hub}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SSL
      ssl.endpoint.identification.algorithm: ""
    ssl:
      trust-store-location: classpath:ssl/kafka.server.truststore.jks
      trust-store-password: ${TRUST_STORE_PASSWORD}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        max.block.ms: 10000
        max.in.flight.requests.per.connection: 5
        retries: 3
        delivery.timeout.ms: 120000
    consumer:
      group-id: hub-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 300000
    listener:
      ack-mode: manual
      concurrency: 3

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:18761/eureka}

server:
  port: 18100

topics:
  order:
    pending: ${TOPICS_ORDER_PENDING:prod-order-pending}
  hub:
    updated: ${TOPICS_HUB_UPDATED:hub-update-topic}
    stock-updated: ${TOPICS_HUB_STOCK_UPDATED:prod-hub-stock-updated}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
