spring:
  application:
    name: hub-service
  profiles:
    active: dev
  config:
    import: 'optional:configserver:'

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost:5435/hub}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:18761/eureka}

server:
  port: 18100

topics:
  order:
    pending: ${TOPICS_ORDER_PENDING:prod-order-pending}
  hub:
    updated: ${TOPICS_HUB_UPDATED:hub-updated-topic}
    stock-updated: ${TOPICS_HUB_STOCK_UPDATED:prod-hub-stock-updated}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
